#!/usr/bin/env python3
"""
Regenerate data/publications.yaml from the group's ORCID record.

    python3 tools/orcid_to_yaml.py                 # default ORCID from hugo.toml
    python3 tools/orcid_to_yaml.py 0000-0002-...   # or pass one explicitly

What it does
------------
Reads the ORCID public API (no key needed), pulls every work with its title,
journal, year, type and DOI, and writes data/publications.yaml sorted newest
first.

What it protects
----------------
The `takeaway`, `code` and `data` fields are written by hand and are the whole
point of the publications page. They are matched to the incoming records by DOI
(falling back to a normalised title) and carried over. Nothing you wrote is lost.

Entries that exist locally but not in ORCID — a paper submitted but not yet
deposited, say — are kept and marked `orcid: false`.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Needs PyYAML:  pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "publications.yaml"
API = "https://pub.orcid.org/v3.0"
KEEP = ("takeaway", "code", "data", "axes")


def orcid_from_config():
    text = (ROOT / "hugo.toml").read_text(encoding="utf-8")
    m = re.search(r"orcid\s*=\s*['\"]([0-9X-]+)['\"]", text)
    return m.group(1) if m else None


def get(url):
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def norm(title):
    return re.sub(r"[^a-z0-9]+", "", (title or "").lower())


def extract(summary):
    title = (summary.get("title") or {}).get("title", {}).get("value", "").strip()
    venue = (summary.get("journal-title") or {}).get("value", "") or ""
    year = ((summary.get("publication-date") or {}).get("year") or {}).get("value")
    doi = ""
    for eid in ((summary.get("external-ids") or {}).get("external-id") or []):
        if eid.get("external-id-type") == "doi":
            doi = (eid.get("external-id-value") or "").strip()
            break
    return {
        "title": title,
        "venue": venue,
        "year": int(year) if year and str(year).isdigit() else 0,
        "type": (summary.get("type") or "article").lower().replace("journal-article", "article"),
        "doi": doi,
        "authors": "",
    }


def main():
    orcid = sys.argv[1] if len(sys.argv) > 1 else orcid_from_config()
    if not orcid:
        sys.exit("No ORCID id found — pass one as an argument.")

    existing = []
    if OUT.exists():
        existing = yaml.safe_load(OUT.read_text(encoding="utf-8")) or []

    by_doi = {e["doi"].lower(): e for e in existing if e.get("doi")}
    by_title = {norm(e.get("title")): e for e in existing}

    print(f"Reading ORCID {orcid} …")
    works = get(f"{API}/{orcid}/works")
    groups = works.get("group", [])
    print(f"  {len(groups)} work groups")

    records, seen = [], set()
    for g in groups:
        summaries = g.get("work-summary") or []
        if not summaries:
            continue
        rec = extract(summaries[0])
        if not rec["title"]:
            continue

        prior = by_doi.get(rec["doi"].lower()) if rec["doi"] else None
        if prior is None:
            prior = by_title.get(norm(rec["title"]))
        if prior:
            for k in KEEP:
                if prior.get(k):
                    rec[k] = prior[k]
            if not rec["authors"] and prior.get("authors"):
                rec["authors"] = prior["authors"]
            seen.add(id(prior))
        records.append(rec)

    orphans = [e for e in existing if id(e) not in seen]
    for e in orphans:
        e["orcid"] = False
        records.append(e)
    if orphans:
        print(f"  kept {len(orphans)} local-only entr{'y' if len(orphans)==1 else 'ies'}")

    records.sort(key=lambda r: (-(r.get("year") or 0), r.get("title", "")))

    header = (
        "# Generated by tools/orcid_to_yaml.py — do not hand-edit the\n"
        "# bibliographic fields, they are overwritten on the next run.\n"
        "# DO hand-edit `takeaway`, `code`, `data` and `axes`: those are\n"
        "# preserved across runs, matched on DOI.\n\n"
    )
    OUT.write_text(
        header + yaml.safe_dump(records, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )
    missing = sum(1 for r in records if not r.get("takeaway"))
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(records)} entries, {missing} without a takeaway.")


if __name__ == "__main__":
    main()
